// <auto-generated />
namespace DeCamaroong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _050920151049addMainImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_050920151049addMainImage));
        
        string IMigrationMetadata.Id
        {
            get { return "201509050349152_050920151049-addMainImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
