// <auto-generated />
namespace DeCamaroong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _29092015 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_29092015));
        
        string IMigrationMetadata.Id
        {
            get { return "201508290243517_29092015"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
