// <auto-generated />
namespace DeCamaroong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _04092015addisNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_04092015addisNew));
        
        string IMigrationMetadata.Id
        {
            get { return "201509040723412_04092015-addisNew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
